query Projects($slug: String!){
    projects( where: {slug: $slug}){
		Title
        Subtitle
        What
        When
        Who
        How
        Urllink
        Url
        Preview{
            url
        }
        Gallery{
            images{
                url
                name
            }
        }
        Nextproject{
          Title
					slug
        }
    }
}
