query Projects{
    projects{
		Title
        What
        When
        Who
        How
        Preview{
            url
        }
        Gallery{
            images{
                url
            }
        }
    }
}